thunder:
  endpoint: "http://localhost:8080"
  user-key: "lightning"
  user-secret: "secret"

server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

# Approved Authentication Credentials
approved-keys:
  - application: lightning
    secret: secret
  - application: lightning
    secret: secret2

# Application Auth Keys
facebook-auth:
    app-id: 896501930437172
    app-secret: 303d6076cc840d8e7bc5d36b2cb9fbc6
