# Thunder Access
thunder:
  endpoint: http://localhost:8080
  user-key: lightning
  user-secret: secret

# Approved Authentication Credentials
approved-keys:
  - application: application
    secret: secret

# Application Auth Keys
facebook:
  app-id:
  app-secret:

twitter:
  app-key:
  app-secret:

# Application Configuration
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
  requestLog:
    appenders:
      - type: file
        currentLogFilename: var/log/lightning-requests.log
        archivedLogFilenamePattern: var/log/lightning-requests-%d.log

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: var/log/lightning.log
      archivedLogFilenamePattern: var/log/lightning-%d.log