# Thunder Access
thunder:
  endpoint: http://thunder.nickeckert.com
  user-key: lightning
  user-secret: secret

# Approved Authentication Credentials
approved-keys:
  - application: application
    secret: secret

# Application Auth Keys
facebook:
  app-id:
  app-secret:

twitter:
  app-key:
  app-secret:

dropbox:
  app-key:
  app-secret:

# Application Configuration
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001