# Thunder Access
thunder:
  endpoint: http://localhost:8080
  user-key: application
  user-secret: secret

# Approved Authentication Credentials
approved-keys:
  - application: application
    secret: secret

# Application Auth Keys
facebook:
  app-id: 896501930437172
  app-secret: 303d6076cc840d8e7bc5d36b2cb9fbc6

twitter:
  app-key: FYd4qK3yLdGs6BQ4BaaqfkDSJ
  app-secret: aS2zYpyH9ddtyt5UHoCnu125wFPEY3maLvNKg4dsHWTEqomeRn

# Application Configuration
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001